version: '3.9'

networks:
  zammad-net:

volumes:
  zammad_data:
  postgres_data:
  elastic_data:
  certbot_conf:
  certbot_webroot:

services:
  postgres:
    container_name: postgres
    build:
      context: ./services
      dockerfile: postgres/Dockerfile
    image: ${DOCKER_REGISTRY:-local}/postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-zammad_production}
      POSTGRES_USER: ${POSTGRES_USER:-zammad}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zammad}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zammad-net

  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./services
      dockerfile: elasticsearch/Dockerfile
    image: ${DOCKER_REGISTRY:-local}/elasticsearch:latest
    restart: unless-stopped
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: ${ES_JAVA_OPTS:-"-Xms512m -Xmx512m"}
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - zammad-net

  zammad:
    container_name: zammad
    build:
      context: ./services
      dockerfile: zammad/Dockerfile
    image: ${DOCKER_REGISTRY:-local}/zammad:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - elasticsearch
    environment:
      POSTGRESQL_HOST: postgres
      POSTGRESQL_USER: ${POSTGRES_USER:-zammad}
      POSTGRESQL_PASS: ${POSTGRES_PASSWORD:-zammad}
      POSTGRESQL_DB: ${POSTGRES_DB:-zammad_production}
      ELASTICSEARCH_HOST: elasticsearch
      ZAMMAD_RAILS_TRUSTED_PROXIES: 0.0.0.0/0
      ZAMMAD_FQDN: ${REMOTE_DOMAIN:-localhost}
    env_file:
      - .env
    volumes:
      - zammad_data:/opt/zammad
    networks:
      - zammad-net

  nginx:
    container_name: nginx
    build:
      context: ./services
      dockerfile: nginx/Dockerfile
    image: ${DOCKER_REGISTRY:-local}/nginx:latest
    restart: unless-stopped
    depends_on:
      - zammad
    environment:
      REMOTE_DOMAIN: ${REMOTE_DOMAIN:-localhost}
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - zammad-net

  certbot:
    container_name: certbot
    build:
      context: ./services
      dockerfile: certbot/Dockerfile
    image: ${DOCKER_REGISTRY:-local}/certbot:latest
    restart: unless-stopped
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    entrypoint: >
      /bin/sh -c 'trap exit TERM; while :; do
        certbot renew;
        sleep 12h & wait $${!};
      done;'
    networks:
      - zammad-net

  wiki:
    container_name: wiki
    build:
      context: .
      dockerfile: services/wiki/Dockerfile
    image: ${DOCKER_REGISTRY:-local}/wiki:latest
    restart: unless-stopped
    networks:
      - zammad-net
