version: '3.9'

networks:
  zammad-net:

volumes:
  zammad_data:
  postgres_data:
  elastic_data:
  certbot_conf:
  certbot_www:

services:
  postgresql:
    build: ./services/postgresql
    image: ${DOCKER_REGISTRY}/postgresql:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zammad-net

  elasticsearch:
    build: ./services/elasticsearch
    image: ${DOCKER_REGISTRY}/elasticsearch:latest
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - zammad-net

  zammad:
    build: ./services/zammad
    image: ${DOCKER_REGISTRY}/zammad:latest
    restart: always
    depends_on:
      - postgresql
      - elasticsearch
    environment:
      POSTGRESQL_HOST: postgresql
      ELASTICSEARCH_HOST: elasticsearch
      ZAMMAD_RAILS_TRUSTED_PROXIES: 0.0.0.0/0
      ZAMMAD_FQDN: ${REMOTE_DOMAIN}
    env_file:
      - .env
    volumes:
      - zammad_data:/opt/zammad
    networks:
      - zammad-net

  nginx:
    build: ./services/nginx
    image: ${DOCKER_REGISTRY}/nginx:latest
    depends_on:
      - zammad
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - zammad-net

  certbot:
    build: ./services/certbot
    image: ${DOCKER_REGISTRY}/certbot:latest
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - zammad-net
