site_name: Zammad Ticketing Wiki
nav:
  - Home: docs/index.md
  - Deployment: docs/deployment.md
  - CI/CD Pipeline: docs/ci-cd-pipeline.md
  - Authentication: docs/authentication.md
  - Email Integration: docs/email-integration.md
  - Branding: docs/branding.md
  - Certbot: docs/certbot.md
  - Certbot Setup: docs/certbot-setup.md
  - Certbot Debug: docs/certbot-debug.md
  - NGINX Certbot: docs/nginx-certbot.md
  - Secrets: docs/secrets.md
  - First Run: docs/first-run.md
  - First Run Checks: docs/first-run-checks.md
  - Troubleshooting: docs/troubleshooting.md
  - Zammad: docs/zammad.md
  - Homepage: docs/homepage.md
  - Agent Guide: docs/agent_prompt.md
