site_name: Zammad Ticketing Wiki
nav:
  - Home: index.md
  - Main README: README/index.md
  - Deployment: deployment.md
  - CI/CD Pipeline: ci-cd-pipeline.md
  - Authentication: authentication.md
  - Email Integration: email-integration.md
  - Branding: branding.md
  - Certbot: certbot.md
  - Certbot Setup: certbot-setup.md
  - Certbot Debug: certbot-debug.md
  - NGINX Certbot: nginx-certbot.md
  - Secrets: secrets.md
  - First Run: first-run.md
  - First Run Checks: first-run-checks.md
  - Troubleshooting: troubleshooting.md
  - Zammad: zammad.md
  - Homepage: homepage.md
  - Agent Guide: agent_prompt.md
